partitions: 
    short: "cpu_short"
    medium: "cpu_medium"
    long: "cpu_long"
    very_short: "cpu_dev"

REFERENCE_GENOME_NAME: "hg19"
ALIGN_THREADS: 8


## Container paths & versions
MUTECT_VERSION: "4.4.0.0"
SRATOOLS_VERSION: "3.0.1"

## Analysis paths
TEMP_DIR: "/tmp/"
## Resource paths
# Probably add these as a module sometime?
ALN_REFERENCES: ## Ensure that these also have BWA indices
  hg19: "/path/to/hg19.fa" 
  hg38: "/path/to/hg38.fa"

FA_PATHS:
  hg19: "/path/to/hg19.fa" 
  hg38: "/path/to/hg38.fa"

db: "metadb"

bench: False

chromosomes:
  hg19: 
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "X"
  hg38:
    - "chr1"
    - "chr2"
    - "chr3"
    - "chr4"
    - "chr5"
    - "chr6"
    - "chr7"
    - "chr8"
    - "chr9"
    - "chr10"
    - "chr11"
    - "chr12"
    - "chr13"
    - "chr14"
    - "chr15"
    - "chr16"
    - "chr17"
    - "chr18"
    - "chr19"
    - "chr20"
    - "chr21"
    - "chr22"
    - "chrX"